### ISSUE TITLE
GEOSException only on a raspberry Pi

### ISSUE THREAD

**Issue by Stefal** [Cartocite/osmada#24]
Hi,

I tried to filter an Adiff on a freshly installed Raspberry Pi 3 (raspbian stretch 9.4), and I got this error:
django.contrib.gis.geos.error.GEOSException: Error encountered checking Geometry returned from GEOS C function "GEOSWKBReader_readHEX_r"

But the same process work on Ubuntu 16.04
```
['/home/osmada/scripts/filters/venv/bin/python', '/home/osmada/scripts/filters/manage.py', 'workflow', 'cartoveloidf', '--input-paths', '1641193 - Paris.osm', '--output-paths', '/home/osmada/scripts/2018-03-06_2018-03-19/data/AnalyzedCSV/1641193 - Paris.csv', '/home/osmada/scripts/2018-03-06_2018-03-19/data/Adiff/1641193 - Paris.osm']
INFO 2018-03-20 15:25:30,016 [1] Running workflow cartoveloidf…
INFO 2018-03-20 15:25:30,017 Importing from "1641193 - Paris.osm"
INFO 2018-03-20 16:03:28,218 Exporting to "/home/osmada/scripts/2018-03-06_2018-03-19/data/AnalyzedCSV/1641193 - Paris.csv"
INFO 2018-03-20 16:03:45,819 Exporting to "/home/osmada/scripts/2018-03-06_2018-03-19/data/Adiff/1641193 - Paris.osm"
GEOS_ERROR: ParseException: Invalid HEX char

Traceback (most recent call last):
  File "/home/osmada/scripts/filters/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/home/osmada/scripts/filters/workflows/management/commands/workflow.py", line 78, in handle
    workflow.run(input_paths, output_paths)
  File "/home/osmada/scripts/filters/workflows/models.py", line 78, in run
    output = step.instance.run(qs)
  File "/home/osmada/scripts/filters/osmdata/exporters.py", line 53, in run
    {'diff': diff}
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/defaulttags.py", line 314, in render
    return nodelist.render(context)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 194, in render
    return template.render(context)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/defaulttags.py", line 314, in render
    return nodelist.render(context)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 194, in render
    return template.render(context)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/template/defaulttags.py", line 168, in render
    len_values = len(values)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/db/models/query.py", line 254, in __len__
    self._fetch_all()
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/db/models/query.py", line 62, in __iter__
    for row in compiler.results_iter(results):
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1009, in apply_converters
    value = converter(value, expression, connection)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/contrib/gis/db/backends/spatialite/operations.py", line 204, in converter
    return None if value is None else GEOSGeometryBase(read(value), geom_class)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/contrib/gis/geos/prototypes/io.py", line 151, in read
    return wkb_reader_read_hex(self.ptr, wkb, len(wkb))
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/contrib/gis/geos/libgeos.py", line 155, in __call__
    return self.func(*args, **kwargs)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/contrib/gis/geos/prototypes/threadsafe.py", line 48, in __call__
    return self.cfunc(self.thread_context.handle.ptr, *args)
  File "/home/osmada/scripts/filters/venv/lib/python3.5/site-packages/django/contrib/gis/geos/prototypes/errcheck.py", line 32, in check_geom
    raise GEOSException('Error encountered checking Geometry returned from GEOS C function "%s".' % func.__name__)
django.contrib.gis.geos.error.GEOSException: Error encountered checking Geometry returned from GEOS C function "GEOSWKBReader_readHEX_r".
osmada processing ended
```

**Comment by Stefal** [comment]
unit test result on raspbian:
```
============================= test session starts ==============================
platform linux -- Python 3.5.3, pytest-3.5.0, py-1.5.3, pluggy-0.6.0
Django settings: osmada.base_settings (from ini file)
rootdir: /home/osmada/scripts/filters, inifile: setup.cfg
plugins: django-3.1.2
collected 74 items

diffanalysis/tests.py ..............                                     [ 18%]
osmdata/tests/test_exporters.py ..                                       [ 21%]
osmdata/tests/test_filters.py ...................                        [ 47%]
osmdata/tests/test_importers.py ....                                     [ 52%]
osmdata/tests/test_models.py .........                                   [ 64%]
osmdata/tests/test_parsers.py ......F.FF......                           [ 86%]
osmdata/tests/test_patchers.py ..                                        [ 89%]
osmdata/tests/test_views.py .                                            [ 90%]
workflows/tests.py .......                                               [100%]

=================================== FAILURES ===================================
_________________ OSMElementsParserTest.test_osmelement_parser _________________

self = <osmdata.tests.test_parsers.OSMElementsParserTest testMethod=test_osmelement_parser>

    def test_osmelement_parser(self):
        # Done here with nodes as example, but this part is generic osm element parsing
        element = minidom_parse_fragment("""
              <node id="3497428295" lat="48.7954702" lon="2.1355157" version="6" timestamp="2016-09-10T14:41:56Z" changeset="42060502" uid="4540825" user="Eunjeung Yu"></node>""")
        node_parser = NodeParser(element)
        node = node_parser.parse()
        # FIXME: this refresh may not be necessary if the parser does input typing
>       node.refresh_from_db()

osmdata/tests/test_parsers.py:58: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
venv/lib/python3.5/site-packages/django/db/models/base.py:616: in refresh_from_db
    db_instance = db_instance_qs.get()
venv/lib/python3.5/site-packages/django/db/models/query.py:397: in get
    num = len(clone)
venv/lib/python3.5/site-packages/django/db/models/query.py:254: in __len__
    self._fetch_all()
venv/lib/python3.5/site-packages/django/db/models/query.py:1179: in _fetch_all
    self._result_cache = list(self._iterable_class(self))
venv/lib/python3.5/site-packages/django/db/models/query.py:62: in __iter__
    for row in compiler.results_iter(results):
venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py:1009: in apply_converters
    value = converter(value, expression, connection)
venv/lib/python3.5/site-packages/django/contrib/gis/db/backends/spatialite/operations.py:204: in converter
    return None if value is None else GEOSGeometryBase(read(value), geom_class)
venv/lib/python3.5/site-packages/django/contrib/gis/geos/prototypes/io.py:151: in read
    return wkb_reader_read_hex(self.ptr, wkb, len(wkb))
venv/lib/python3.5/site-packages/django/contrib/gis/geos/libgeos.py:155: in __call__
    return self.func(*args, **kwargs)
venv/lib/python3.5/site-packages/django/contrib/gis/geos/prototypes/threadsafe.py:48: in __call__
    return self.cfunc(self.thread_context.handle.ptr, *args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

result = <django.contrib.gis.geos.libgeos.LP_GEOSGeom_t object at 0x6bfabe90>
func = <_FuncPtr object at 0x6bf90880>
cargs = (<django.contrib.gis.geos.libgeos.LP_GEOSContextHandle_t object at 0x6c1598a0>, <django.contrib.gis.geos.prototypes.io.LP_WKBReader_st object at 0x6c159da0>, b'0101000020110F00007FB09529E4040D414C0021FDF8CD5741', 50)

    def check_geom(result, func, cargs):
        "Error checking on routines that return Geometries."
        if not result:
>           raise GEOSException('Error encountered checking Geometry returned from GEOS C function "%s".' % func.__name__)
E           django.contrib.gis.geos.error.GEOSException: Error encountered checking Geometry returned from GEOS C function "GEOSWKBReader_readHEX_r".

venv/lib/python3.5/site-packages/django/contrib/gis/geos/prototypes/errcheck.py:32: GEOSException
------------------------------ Captured log call -------------------------------
libgeos.py                 100 ERROR    GEOS_ERROR: ParseException: Invalid HEX char
____________________ OSMElementsParserTest.test_way_parser _____________________

self = <osmdata.tests.test_parsers.OSMElementsParserTest testMethod=test_way_parser>

    def test_way_parser(self):
        element = minidom_parse_fragment("""
              <way id="444967525" version="1" timestamp="2016-09-29T20:39:04Z" changeset="42528786" uid="677099" user="Yann_L">
                <bounds minlat="48.8874273" minlon="2.3140091" maxlat="48.8874563" maxlon="2.3140648"/>
                <nd ref="4424244203" lat="48.8874563" lon="2.3140540"/>
                <nd ref="4424244201" lat="48.8874414" lon="2.3140648"/>
              </way>
            """)
        way_parser = WayParser(element)
        way = way_parser.parse()
        self.assertIsInstance(way, Way)
        self.assertIsInstance(way.bounds, Bounds)
>       self.assertIsInstance(way.nodes.first(), Node)

osmdata/tests/test_parsers.py:92: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
venv/lib/python3.5/site-packages/django/db/models/manager.py:82: in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
venv/lib/python3.5/site-packages/django/db/models/query.py:604: in first
    for obj in (self if self.ordered else self.order_by('pk'))[:1]:
venv/lib/python3.5/site-packages/django/db/models/query.py:272: in __iter__
    self._fetch_all()
venv/lib/python3.5/site-packages/django/db/models/query.py:1179: in _fetch_all
    self._result_cache = list(self._iterable_class(self))
venv/lib/python3.5/site-packages/django/db/models/query.py:62: in __iter__
    for row in compiler.results_iter(results):
venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py:1009: in apply_converters
    value = converter(value, expression, connection)
venv/lib/python3.5/site-packages/django/contrib/gis/db/backends/spatialite/operations.py:204: in converter
    return None if value is None else GEOSGeometryBase(read(value), geom_class)
venv/lib/python3.5/site-packages/django/contrib/gis/geos/prototypes/io.py:151: in read
    return wkb_reader_read_hex(self.ptr, wkb, len(wkb))
venv/lib/python3.5/site-packages/django/contrib/gis/geos/libgeos.py:155: in __call__
    return self.func(*args, **kwargs)
venv/lib/python3.5/site-packages/django/contrib/gis/geos/prototypes/threadsafe.py:48: in __call__
    return self.cfunc(self.thread_context.handle.ptr, *args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

result = <django.contrib.gis.geos.libgeos.LP_GEOSGeom_t object at 0x6be9de90>
func = <_FuncPtr object at 0x6bf90880>
cargs = (<django.contrib.gis.geos.libgeos.LP_GEOSContextHandle_t object at 0x6c1598a0>, <django.contrib.gis.geos.prototypes.io.LP_WKBReader_st object at 0x6c159da0>, b'0101000020110F00000DF4EA80FA710F41FBDC40A72ADD5741', 50)

    def check_geom(result, func, cargs):
        "Error checking on routines that return Geometries."
        if not result:
>           raise GEOSException('Error encountered checking Geometry returned from GEOS C function "%s".' % func.__name__)
E           django.contrib.gis.geos.error.GEOSException: Error encountered checking Geometry returned from GEOS C function "GEOSWKBReader_readHEX_r".

venv/lib/python3.5/site-packages/django/contrib/gis/geos/prototypes/errcheck.py:32: GEOSException
------------------------------ Captured log call -------------------------------
libgeos.py                 100 ERROR    GEOS_ERROR: ParseException: Invalid HEX char
____________ RelationParserTest.test_relation_simple_members_parser ____________

self = <osmdata.tests.test_parsers.RelationParserTest testMethod=test_relation_simple_members_parser>

    def test_relation_simple_members_parser(self):
        element = minidom_parse_fragment("""
              <relation id="3995957" version="6" timestamp="2016-04-18T11:22:55Z" changeset="38664682" uid="15908" user="cantece">
                <bounds minlat="48.3939579" minlon="2.7619426" maxlat="48.3946877" maxlon="2.7667246"/>
                <member type="node" ref="3571536293" role="" lat="48.3943179" lon="2.7640013"/>
              </relation>
            """)
        relation_parser = RelationParser(element)
        relation = relation_parser.parse()
        self.assertIsInstance(relation, Relation)
        self.assertEqual(relation.members.count(), 1)
    
        first_member = relation.members.first()
        self.assertIsInstance(first_member, RelationMember)
        self.assertEqual(first_member.role, '')
>       self.assertEqual(first_member.element.osmid, Node.objects.first().osmid)

osmdata/tests/test_parsers.py:128: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
venv/lib/python3.5/site-packages/django/db/models/manager.py:82: in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
venv/lib/python3.5/site-packages/django/db/models/query.py:604: in first
    for obj in (self if self.ordered else self.order_by('pk'))[:1]:
venv/lib/python3.5/site-packages/django/db/models/query.py:272: in __iter__
    self._fetch_all()
venv/lib/python3.5/site-packages/django/db/models/query.py:1179: in _fetch_all
    self._result_cache = list(self._iterable_class(self))
venv/lib/python3.5/site-packages/django/db/models/query.py:62: in __iter__
    for row in compiler.results_iter(results):
venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py:1009: in apply_converters
    value = converter(value, expression, connection)
venv/lib/python3.5/site-packages/django/contrib/gis/db/backends/spatialite/operations.py:204: in converter
    return None if value is None else GEOSGeometryBase(read(value), geom_class)
venv/lib/python3.5/site-packages/django/contrib/gis/geos/prototypes/io.py:151: in read
    return wkb_reader_read_hex(self.ptr, wkb, len(wkb))
venv/lib/python3.5/site-packages/django/contrib/gis/geos/libgeos.py:155: in __call__
    return self.func(*args, **kwargs)
venv/lib/python3.5/site-packages/django/contrib/gis/geos/prototypes/threadsafe.py:48: in __call__
    return self.cfunc(self.thread_context.handle.ptr, *args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

result = <django.contrib.gis.geos.libgeos.LP_GEOSGeom_t object at 0x6bc563a0>
func = <_FuncPtr object at 0x6bf90880>
cargs = (<django.contrib.gis.geos.libgeos.LP_GEOSContextHandle_t object at 0x6c1598a0>, <django.contrib.gis.geos.prototypes.io.LP_WKBReader_st object at 0x6c159da0>, b'0101000020110F00000E7D7BDE9CC71241AD5EF4F2088C5741', 50)

    def check_geom(result, func, cargs):
        "Error checking on routines that return Geometries."
        if not result:
>           raise GEOSException('Error encountered checking Geometry returned from GEOS C function "%s".' % func.__name__)
E           django.contrib.gis.geos.error.GEOSException: Error encountered checking Geometry returned from GEOS C function "GEOSWKBReader_readHEX_r".

venv/lib/python3.5/site-packages/django/contrib/gis/geos/prototypes/errcheck.py:32: GEOSException
------------------------------ Captured log call -------------------------------
libgeos.py                 100 ERROR    GEOS_ERROR: ParseException: Invalid HEX char
==================== 3 failed, 71 passed in 165.01 seconds =====================
```
