### ISSUE TITLE
crash with adiffexporter

### ISSUE THREAD

**Issue by Stefal** [Cartocite/osmada#5]
With the adiffexporter, I get a crash with the attached local_settings and some osm file, like the one attached.
Here is the traceback:
`[3] Writing output...
Traceback (most recent call last):
  File "/home/stephane/Osmada/osmada/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/stephane/Osmada/osmada/workflows/management/commands/workflow.py", line 49, in handle
    print(workflow.write_output())
  File "/home/stephane/Osmada/osmada/workflows/models.py", line 55, in write_output
    return self.ExporterClass().run(self.out_qs)
  File "/home/stephane/Osmada/osmada/osmdata/exporters.py", line 53, in run
    {'diff': diff}
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/defaulttags.py", line 216, in render
    nodelist.append(node.render_annotated(context))
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 216, in render
    return template.render(context)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 216, in render
    return template.render(context)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 154, in render
    compiled_parent = self.get_parent(context)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 151, in get_parent
    return self.find_template(parent, context)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 131, in find_template
    template_name, skip=history,
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/base.py", line 230, in compile_nodelist
    return parser.parse()
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/base.py", line 486, in parse
    raise self.error(token, e)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/base.py", line 484, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/base.py", line 694, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/home/stephane/Osmada/osmada/venv/lib/python3.5/site-packages/django/template/base.py", line 606, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'lowercase'
`

cc @JocelynDelalande 

[local_settings.py.zip](https://github.com/Cartocite/osmada/files/952123/local_settings.py.zip)
[Clamart.osm.zip](https://github.com/Cartocite/osmada/files/952103/Clamart.osm.zip)

**Comment by JocelynDelalande** [comment]
@Stefal thanks for reporting. I'm working on it.

**Comment by JocelynDelalande** [comment]
@Stefal fixed, could you confirm ? 

(I tested with your local_settings and data, it was fine, after the fix).

**Comment by Stefal** [comment]
I confirm, it works !
Thank you @JocelynDelalande
